#cloud-config 
users:
  - name: nutanix
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
chpasswd:
  list: |
    nutanix:nutanix/4u
  expire: False
ssh_pwauth: true"
packages:
  - git
  - terraform
runcmd:
  - mkdir /home/nutanix/Getting_Started_With_Terraform_and_Nutanix
  - chwon nutanix:nutanix /home/nutanix/Getting_Started_With_Terraform_and_Nutanix
  - git clone https://github.com/TioTony/Getting_Started_With_Terraform_and_Nutanix /home/nutanix/Getting_Started_With_Terraform_and_Nutanix