#cloud-config 
users:
  - name: nutanix
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
chpasswd:
  list: |
    nutanix:nutanix/4u
  expire: False
ssh_pwauth: true"
packages:
  - git
runcmd:
  - yum install -y yum-utils
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  - yum install -y terraform
  - mkdir /home/nutanix/Getting_Started_With_Terraform_and_Nutanix
  - git clone https://github.com/TioTony/Getting_Started_With_Terraform_and_Nutanix /home/nutanix/Getting_Started_With_Terraform_and_Nutanix
  - chown -R nutanix:nutanix /home/nutanix/Getting_Started_With_Terraform_and_Nutanix
